### ISSUE TITLE
carousel image aspect ratio

### ISSUE THREAD

**Issue by annanyadas** [annanyadas/practice#1]
the carousel image can have a max height of 665px which breaks its aspect ratio. fix the aspect ratio without changing the max height.
if some portion of image is cut off to maintain the aspect ratio it is fine.

**Comment by shivampatel19** [comment]
Do you want to remove horizontal scoll?

**Comment by annanyadas** [comment]
is the scroll for a single image or the carousel ?

**Comment by annanyadas** [comment]
i merge your pull request .Thank you and Great Job

**Comment by farnam13245** [comment]
Thank you I appreciate it!
