### ISSUE TITLE
Change Nav

### ISSUE THREAD

**Issue by annanyadas** [annanyadas/practice#10]
Change the navbar brand to a logo instead of a text

**Comment by raaamonnn** [comment]
Hello. I just uploaded a Pull Request for this issue. Thank you.

**Comment by annanyadas** [comment]
Hi @raaamonnn . Great to have you in this issue . i got your PR and you did a wonderful job. but before merging i would like to ask did you add cdn link of jquery before using it moreover the classes like active in the navbar jquery i could not find the class active in the navbar code . So how is it working

**Comment by raaamonnn** [comment]
Hello @annanyadas! Are you talking about the highlight script?   It adds and removes the "active" class that comes from bootstrap if a navbar item is clicked. I thought it was nice to have for now until the actual pages are implemented.

**Comment by annanyadas** [comment]
the script is implemented in jquery and there is no cdn in the index.html for jquery then how it will work?

**Comment by raaamonnn** [comment]
I see what you are saying. Yea I should be using the jquery CDN but for some reason, it is working without it. Does it also work properly on your side? Do you want me to add the CDN?

**Comment by annanyadas** [comment]
no no the behaviour that you are seeing is the default one . you remove the jquery portion and it will still work

**Comment by raaamonnn** [comment]
@annanyadas added a new commit to the PR where I took out the jquery script.

**Comment by annanyadas** [comment]
Thank you . glad to have you on this practice project . I merged your PR
