### ISSUE TITLE
The Contact Form Button is not in the center

### ISSUE THREAD

**Issue by annanyadas** [annanyadas/practice#13]
Make the button in the center and the center should be maintained in  mobile view too

**Comment by ahcodes** [comment]
Hi Ananya, I'd like to take care of this issue. Could you assign me, please? Thanks!

**Comment by annanyadas** [comment]
i assigned it you . Go ahead

**Comment by GaurPeeyush** [comment]
Contact button Issue is fixed.
Now button is center aligned.

**Comment by MathurUtkarsh** [comment]
Contact button is now center aligned.
Issue Solved :)

**Comment by ahcodes** [comment]
Reviewed the code, the button is center aligned.

**Comment by MathurUtkarsh** [comment]
The issue has been solved so please merge my pull request .

**Comment by GaurPeeyush** [comment]
The issue is fixed!
Glad that I could help
You may close this issue!
:)
