### ISSUE TITLE
the photographer list are arrange vertically

### ISSUE THREAD

**Issue by annanyadas** [annanyadas/practice#2]
change the arrangement of the photographer list from vertical to horizontal . Make sure it stays responsive

**Comment by shivampatel19** [comment]
I want to do it. Assign it to me please.

**Comment by ritikakhandelwal-17** [comment]
I can solve this issue using flexbox . Please assign it to me.

**Comment by ritikakhandelwal-17** [comment]
Please assign this issue under me . I have solved it and made a pull request
